package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CaseType generated by hbm2java
 */
public class CaseType  implements java.io.Serializable {


     private Integer id;
     private Integer type;
     private Set<GrnLog> grnLogs = new HashSet<GrnLog>(0);

    public CaseType() {
    }

    public CaseType(Integer type, Set<GrnLog> grnLogs) {
       this.type = type;
       this.grnLogs = grnLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Set<GrnLog> getGrnLogs() {
        return this.grnLogs;
    }
    
    public void setGrnLogs(Set<GrnLog> grnLogs) {
        this.grnLogs = grnLogs;
    }




}


