package pojo;
// Generated Jun 6, 2018 3:33:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CaseType generated by hbm2java
 */
public class CaseType  implements java.io.Serializable {


     private Integer id;
     private Integer type;
     private Set grnLogs = new HashSet(0);

    public CaseType() {
    }

    public CaseType(Integer type, Set grnLogs) {
       this.type = type;
       this.grnLogs = grnLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Set getGrnLogs() {
        return this.grnLogs;
    }
    
    public void setGrnLogs(Set grnLogs) {
        this.grnLogs = grnLogs;
    }




}


