package pojo;
// Generated Jun 5, 2018 11:17:44 PM by Hibernate Tools 4.3.1



/**
 * CaseType generated by hbm2java
 */
public class CaseType  implements java.io.Serializable {


     private Integer id;
     private Integer type;

    public CaseType() {
    }

    public CaseType(Integer type) {
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }




}


