package pojo;
// Generated May 22, 2018 8:29:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CustomerCredit generated by hbm2java
 */
public class CustomerCredit  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Double amount;
     private Date date;

    public CustomerCredit() {
    }

	
    public CustomerCredit(Customer customer) {
        this.customer = customer;
    }
    public CustomerCredit(Customer customer, Double amount, Date date) {
       this.customer = customer;
       this.amount = amount;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


