package pojo;
// Generated May 18, 2018 5:44:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CustomerDebit generated by hbm2java
 */
public class CustomerDebit  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Double amount;
     private Date date;

    public CustomerDebit() {
    }

	
    public CustomerDebit(Customer customer) {
        this.customer = customer;
    }
    public CustomerDebit(Customer customer, Double amount, Date date) {
       this.customer = customer;
       this.amount = amount;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


