package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dilivery generated by hbm2java
 */
public class Dilivery  implements java.io.Serializable {


     private Integer id;
     private Route route;
     private Vehicle vehicle;
     private Date date;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);
     private Set<OngoingDilivery> ongoingDiliveries = new HashSet<OngoingDilivery>(0);
     private Set<DiliveryEmployeeLog> diliveryEmployeeLogs = new HashSet<DiliveryEmployeeLog>(0);
     private Set<DiliveryItemLog> diliveryItemLogs = new HashSet<DiliveryItemLog>(0);
     private Set<DiliveryLoad> diliveryLoads = new HashSet<DiliveryLoad>(0);

    public Dilivery() {
    }

	
    public Dilivery(Route route, Vehicle vehicle) {
        this.route = route;
        this.vehicle = vehicle;
    }
    public Dilivery(Route route, Vehicle vehicle, Date date, Set<Invoice> invoices, Set<OngoingDilivery> ongoingDiliveries, Set<DiliveryEmployeeLog> diliveryEmployeeLogs, Set<DiliveryItemLog> diliveryItemLogs, Set<DiliveryLoad> diliveryLoads) {
       this.route = route;
       this.vehicle = vehicle;
       this.date = date;
       this.invoices = invoices;
       this.ongoingDiliveries = ongoingDiliveries;
       this.diliveryEmployeeLogs = diliveryEmployeeLogs;
       this.diliveryItemLogs = diliveryItemLogs;
       this.diliveryLoads = diliveryLoads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }
    public Vehicle getVehicle() {
        return this.vehicle;
    }
    
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }
    public Set<OngoingDilivery> getOngoingDiliveries() {
        return this.ongoingDiliveries;
    }
    
    public void setOngoingDiliveries(Set<OngoingDilivery> ongoingDiliveries) {
        this.ongoingDiliveries = ongoingDiliveries;
    }
    public Set<DiliveryEmployeeLog> getDiliveryEmployeeLogs() {
        return this.diliveryEmployeeLogs;
    }
    
    public void setDiliveryEmployeeLogs(Set<DiliveryEmployeeLog> diliveryEmployeeLogs) {
        this.diliveryEmployeeLogs = diliveryEmployeeLogs;
    }
    public Set<DiliveryItemLog> getDiliveryItemLogs() {
        return this.diliveryItemLogs;
    }
    
    public void setDiliveryItemLogs(Set<DiliveryItemLog> diliveryItemLogs) {
        this.diliveryItemLogs = diliveryItemLogs;
    }
    public Set<DiliveryLoad> getDiliveryLoads() {
        return this.diliveryLoads;
    }
    
    public void setDiliveryLoads(Set<DiliveryLoad> diliveryLoads) {
        this.diliveryLoads = diliveryLoads;
    }




}


