package pojo;
// Generated May 22, 2018 8:34:55 PM by Hibernate Tools 4.3.1



/**
 * DiliveryItemLog generated by hbm2java
 */
public class DiliveryItemLog  implements java.io.Serializable {


     private Integer id;
     private Dilivery dilivery;
     private Product product;
     private int grnLogId;
     private Double fullQty;
     private Double remainingQuantity;

    public DiliveryItemLog() {
    }

	
    public DiliveryItemLog(Dilivery dilivery, Product product, int grnLogId) {
        this.dilivery = dilivery;
        this.product = product;
        this.grnLogId = grnLogId;
    }
    public DiliveryItemLog(Dilivery dilivery, Product product, int grnLogId, Double fullQty, Double remainingQuantity) {
       this.dilivery = dilivery;
       this.product = product;
       this.grnLogId = grnLogId;
       this.fullQty = fullQty;
       this.remainingQuantity = remainingQuantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dilivery getDilivery() {
        return this.dilivery;
    }
    
    public void setDilivery(Dilivery dilivery) {
        this.dilivery = dilivery;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getGrnLogId() {
        return this.grnLogId;
    }
    
    public void setGrnLogId(int grnLogId) {
        this.grnLogId = grnLogId;
    }
    public Double getFullQty() {
        return this.fullQty;
    }
    
    public void setFullQty(Double fullQty) {
        this.fullQty = fullQty;
    }
    public Double getRemainingQuantity() {
        return this.remainingQuantity;
    }
    
    public void setRemainingQuantity(Double remainingQuantity) {
        this.remainingQuantity = remainingQuantity;
    }




}


