package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GrnLog generated by hbm2java
 */
public class GrnLog  implements java.io.Serializable {


     private Integer id;
     private CaseType caseType;
     private Grn grn;
     private Product product;
     private Double buyingPrice;
     private Double quantity;
     private Double remainingQuantity;
     private Double discount;
     private Double total;
     private Set<DiliveryItemLog> diliveryItemLogs = new HashSet<DiliveryItemLog>(0);

    public GrnLog() {
    }

	
    public GrnLog(CaseType caseType, Grn grn, Product product) {
        this.caseType = caseType;
        this.grn = grn;
        this.product = product;
    }
    public GrnLog(CaseType caseType, Grn grn, Product product, Double buyingPrice, Double quantity, Double remainingQuantity, Double discount, Double total, Set<DiliveryItemLog> diliveryItemLogs) {
       this.caseType = caseType;
       this.grn = grn;
       this.product = product;
       this.buyingPrice = buyingPrice;
       this.quantity = quantity;
       this.remainingQuantity = remainingQuantity;
       this.discount = discount;
       this.total = total;
       this.diliveryItemLogs = diliveryItemLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CaseType getCaseType() {
        return this.caseType;
    }
    
    public void setCaseType(CaseType caseType) {
        this.caseType = caseType;
    }
    public Grn getGrn() {
        return this.grn;
    }
    
    public void setGrn(Grn grn) {
        this.grn = grn;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getBuyingPrice() {
        return this.buyingPrice;
    }
    
    public void setBuyingPrice(Double buyingPrice) {
        this.buyingPrice = buyingPrice;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public Double getRemainingQuantity() {
        return this.remainingQuantity;
    }
    
    public void setRemainingQuantity(Double remainingQuantity) {
        this.remainingQuantity = remainingQuantity;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set<DiliveryItemLog> getDiliveryItemLogs() {
        return this.diliveryItemLogs;
    }
    
    public void setDiliveryItemLogs(Set<DiliveryItemLog> diliveryItemLogs) {
        this.diliveryItemLogs = diliveryItemLogs;
    }




}


