package pojo;
// Generated May 22, 2018 8:34:55 PM by Hibernate Tools 4.3.1



/**
 * InvoiceHasCheques generated by hbm2java
 */
public class InvoiceHasCheques  implements java.io.Serializable {


     private Integer idInvoiceHasCheques;
     private Cheques cheques;
     private Invoice invoice;

    public InvoiceHasCheques() {
    }

    public InvoiceHasCheques(Cheques cheques, Invoice invoice) {
       this.cheques = cheques;
       this.invoice = invoice;
    }
   
    public Integer getIdInvoiceHasCheques() {
        return this.idInvoiceHasCheques;
    }
    
    public void setIdInvoiceHasCheques(Integer idInvoiceHasCheques) {
        this.idInvoiceHasCheques = idInvoiceHasCheques;
    }
    public Cheques getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Cheques cheques) {
        this.cheques = cheques;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }




}


