package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1



/**
 * InvoiceLog generated by hbm2java
 */
public class InvoiceLog  implements java.io.Serializable {


     private Integer id;
     private Invoice invoice;
     private Product product;
     private Double qty;
     private Double sellingPrice;
     private Double discount;
     private Double total;

    public InvoiceLog() {
    }

	
    public InvoiceLog(Invoice invoice, Product product) {
        this.invoice = invoice;
        this.product = product;
    }
    public InvoiceLog(Invoice invoice, Product product, Double qty, Double sellingPrice, Double discount, Double total) {
       this.invoice = invoice;
       this.product = product;
       this.qty = qty;
       this.sellingPrice = sellingPrice;
       this.discount = discount;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


