package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Dilivery dilivery;
     private Date date;
     private Double fulltotal;
     private Double cash;
     private Double cheack;
     private Set<InvoiceHasCheques> invoiceHasChequeses = new HashSet<InvoiceHasCheques>(0);
     private Set<InvoiceLog> invoiceLogs = new HashSet<InvoiceLog>(0);

    public Invoice() {
    }

	
    public Invoice(Customer customer, Dilivery dilivery) {
        this.customer = customer;
        this.dilivery = dilivery;
    }
    public Invoice(Customer customer, Dilivery dilivery, Date date, Double fulltotal, Double cash, Double cheack, Set<InvoiceHasCheques> invoiceHasChequeses, Set<InvoiceLog> invoiceLogs) {
       this.customer = customer;
       this.dilivery = dilivery;
       this.date = date;
       this.fulltotal = fulltotal;
       this.cash = cash;
       this.cheack = cheack;
       this.invoiceHasChequeses = invoiceHasChequeses;
       this.invoiceLogs = invoiceLogs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Dilivery getDilivery() {
        return this.dilivery;
    }
    
    public void setDilivery(Dilivery dilivery) {
        this.dilivery = dilivery;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getFulltotal() {
        return this.fulltotal;
    }
    
    public void setFulltotal(Double fulltotal) {
        this.fulltotal = fulltotal;
    }
    public Double getCash() {
        return this.cash;
    }
    
    public void setCash(Double cash) {
        this.cash = cash;
    }
    public Double getCheack() {
        return this.cheack;
    }
    
    public void setCheack(Double cheack) {
        this.cheack = cheack;
    }
    public Set<InvoiceHasCheques> getInvoiceHasChequeses() {
        return this.invoiceHasChequeses;
    }
    
    public void setInvoiceHasChequeses(Set<InvoiceHasCheques> invoiceHasChequeses) {
        this.invoiceHasChequeses = invoiceHasChequeses;
    }
    public Set<InvoiceLog> getInvoiceLogs() {
        return this.invoiceLogs;
    }
    
    public void setInvoiceLogs(Set<InvoiceLog> invoiceLogs) {
        this.invoiceLogs = invoiceLogs;
    }




}


