package pojo;
// Generated May 18, 2018 5:44:16 PM by Hibernate Tools 4.3.1



/**
 * OngoingDilivery generated by hbm2java
 */
public class OngoingDilivery  implements java.io.Serializable {


     private Integer id;
     private Dilivery dilivery;
     private Integer status;

    public OngoingDilivery() {
    }

	
    public OngoingDilivery(Dilivery dilivery) {
        this.dilivery = dilivery;
    }
    public OngoingDilivery(Dilivery dilivery, Integer status) {
       this.dilivery = dilivery;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Dilivery getDilivery() {
        return this.dilivery;
    }
    
    public void setDilivery(Dilivery dilivery) {
        this.dilivery = dilivery;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


