package pojo;
// Generated Jun 6, 2018 3:33:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
public class Position  implements java.io.Serializable {


     private Integer id;
     private String positionName;
     private String discription;
     private Set employees = new HashSet(0);

    public Position() {
    }

    public Position(String positionName, String discription, Set employees) {
       this.positionName = positionName;
       this.discription = discription;
       this.employees = employees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPositionName() {
        return this.positionName;
    }
    
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


