package pojo;
// Generated Jun 6, 2018 3:33:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Units units;
     private String name;
     private Double currentStock;
     private Double currentPrice;
     private Set grnLogs = new HashSet(0);
     private Set diliveryItemLogs = new HashSet(0);
     private Set invoiceLogs = new HashSet(0);
     private Set vehicleStocks = new HashSet(0);
     private Set diliveryLoads = new HashSet(0);

    public Product() {
    }

	
    public Product(Units units) {
        this.units = units;
    }
    public Product(Units units, String name, Double currentStock, Double currentPrice, Set grnLogs, Set diliveryItemLogs, Set invoiceLogs, Set vehicleStocks, Set diliveryLoads) {
       this.units = units;
       this.name = name;
       this.currentStock = currentStock;
       this.currentPrice = currentPrice;
       this.grnLogs = grnLogs;
       this.diliveryItemLogs = diliveryItemLogs;
       this.invoiceLogs = invoiceLogs;
       this.vehicleStocks = vehicleStocks;
       this.diliveryLoads = diliveryLoads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getCurrentStock() {
        return this.currentStock;
    }
    
    public void setCurrentStock(Double currentStock) {
        this.currentStock = currentStock;
    }
    public Double getCurrentPrice() {
        return this.currentPrice;
    }
    
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }
    public Set getGrnLogs() {
        return this.grnLogs;
    }
    
    public void setGrnLogs(Set grnLogs) {
        this.grnLogs = grnLogs;
    }
    public Set getDiliveryItemLogs() {
        return this.diliveryItemLogs;
    }
    
    public void setDiliveryItemLogs(Set diliveryItemLogs) {
        this.diliveryItemLogs = diliveryItemLogs;
    }
    public Set getInvoiceLogs() {
        return this.invoiceLogs;
    }
    
    public void setInvoiceLogs(Set invoiceLogs) {
        this.invoiceLogs = invoiceLogs;
    }
    public Set getVehicleStocks() {
        return this.vehicleStocks;
    }
    
    public void setVehicleStocks(Set vehicleStocks) {
        this.vehicleStocks = vehicleStocks;
    }
    public Set getDiliveryLoads() {
        return this.diliveryLoads;
    }
    
    public void setDiliveryLoads(Set diliveryLoads) {
        this.diliveryLoads = diliveryLoads;
    }




}


