package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Units units;
     private String name;
     private Double currentStock;
     private Double currentPrice;
     private Set<GrnLog> grnLogs = new HashSet<GrnLog>(0);
     private Set<DiliveryItemLog> diliveryItemLogs = new HashSet<DiliveryItemLog>(0);
     private Set<InvoiceLog> invoiceLogs = new HashSet<InvoiceLog>(0);
     private Set<VehicleStock> vehicleStocks = new HashSet<VehicleStock>(0);
     private Set<DiliveryLoad> diliveryLoads = new HashSet<DiliveryLoad>(0);

    public Product() {
    }

	
    public Product(Units units) {
        this.units = units;
    }
    public Product(Units units, String name, Double currentStock, Double currentPrice, Set<GrnLog> grnLogs, Set<DiliveryItemLog> diliveryItemLogs, Set<InvoiceLog> invoiceLogs, Set<VehicleStock> vehicleStocks, Set<DiliveryLoad> diliveryLoads) {
       this.units = units;
       this.name = name;
       this.currentStock = currentStock;
       this.currentPrice = currentPrice;
       this.grnLogs = grnLogs;
       this.diliveryItemLogs = diliveryItemLogs;
       this.invoiceLogs = invoiceLogs;
       this.vehicleStocks = vehicleStocks;
       this.diliveryLoads = diliveryLoads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getCurrentStock() {
        return this.currentStock;
    }
    
    public void setCurrentStock(Double currentStock) {
        this.currentStock = currentStock;
    }
    public Double getCurrentPrice() {
        return this.currentPrice;
    }
    
    public void setCurrentPrice(Double currentPrice) {
        this.currentPrice = currentPrice;
    }
    public Set<GrnLog> getGrnLogs() {
        return this.grnLogs;
    }
    
    public void setGrnLogs(Set<GrnLog> grnLogs) {
        this.grnLogs = grnLogs;
    }
    public Set<DiliveryItemLog> getDiliveryItemLogs() {
        return this.diliveryItemLogs;
    }
    
    public void setDiliveryItemLogs(Set<DiliveryItemLog> diliveryItemLogs) {
        this.diliveryItemLogs = diliveryItemLogs;
    }
    public Set<InvoiceLog> getInvoiceLogs() {
        return this.invoiceLogs;
    }
    
    public void setInvoiceLogs(Set<InvoiceLog> invoiceLogs) {
        this.invoiceLogs = invoiceLogs;
    }
    public Set<VehicleStock> getVehicleStocks() {
        return this.vehicleStocks;
    }
    
    public void setVehicleStocks(Set<VehicleStock> vehicleStocks) {
        this.vehicleStocks = vehicleStocks;
    }
    public Set<DiliveryLoad> getDiliveryLoads() {
        return this.diliveryLoads;
    }
    
    public void setDiliveryLoads(Set<DiliveryLoad> diliveryLoads) {
        this.diliveryLoads = diliveryLoads;
    }




}


