package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String discription;
     private Set<Dilivery> diliveries = new HashSet<Dilivery>(0);

    public Route() {
    }

    public Route(String name, String discription, Set<Dilivery> diliveries) {
       this.name = name;
       this.discription = discription;
       this.diliveries = diliveries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Set<Dilivery> getDiliveries() {
        return this.diliveries;
    }
    
    public void setDiliveries(Set<Dilivery> diliveries) {
        this.diliveries = diliveries;
    }




}


