package pojo;
// Generated Jun 6, 2018 3:33:42 PM by Hibernate Tools 4.3.1



/**
 * SupplierHasCheques generated by hbm2java
 */
public class SupplierHasCheques  implements java.io.Serializable {


     private Integer id;
     private Cheques cheques;
     private Supplier supplier;

    public SupplierHasCheques() {
    }

    public SupplierHasCheques(Cheques cheques, Supplier supplier) {
       this.cheques = cheques;
       this.supplier = supplier;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cheques getCheques() {
        return this.cheques;
    }
    
    public void setCheques(Cheques cheques) {
        this.cheques = cheques;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }




}


