package pojo;
// Generated May 22, 2018 8:34:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer id;
     private String vehicleNumber;
     private String discription;
     private Set diliveries = new HashSet(0);
     private Set vehicleStocks = new HashSet(0);

    public Vehicle() {
    }

    public Vehicle(String vehicleNumber, String discription, Set diliveries, Set vehicleStocks) {
       this.vehicleNumber = vehicleNumber;
       this.discription = discription;
       this.diliveries = diliveries;
       this.vehicleStocks = vehicleStocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVehicleNumber() {
        return this.vehicleNumber;
    }
    
    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Set getDiliveries() {
        return this.diliveries;
    }
    
    public void setDiliveries(Set diliveries) {
        this.diliveries = diliveries;
    }
    public Set getVehicleStocks() {
        return this.vehicleStocks;
    }
    
    public void setVehicleStocks(Set vehicleStocks) {
        this.vehicleStocks = vehicleStocks;
    }




}


