package pojo;
// Generated Jun 13, 2018 3:21:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer id;
     private String vehicleNumber;
     private String discription;
     private Set<Dilivery> diliveries = new HashSet<Dilivery>(0);
     private Set<VehicleStock> vehicleStocks = new HashSet<VehicleStock>(0);

    public Vehicle() {
    }

    public Vehicle(String vehicleNumber, String discription, Set<Dilivery> diliveries, Set<VehicleStock> vehicleStocks) {
       this.vehicleNumber = vehicleNumber;
       this.discription = discription;
       this.diliveries = diliveries;
       this.vehicleStocks = vehicleStocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVehicleNumber() {
        return this.vehicleNumber;
    }
    
    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Set<Dilivery> getDiliveries() {
        return this.diliveries;
    }
    
    public void setDiliveries(Set<Dilivery> diliveries) {
        this.diliveries = diliveries;
    }
    public Set<VehicleStock> getVehicleStocks() {
        return this.vehicleStocks;
    }
    
    public void setVehicleStocks(Set<VehicleStock> vehicleStocks) {
        this.vehicleStocks = vehicleStocks;
    }




}


